### ISSUE TITLE
Distribute wheels

### ISSUE THREAD

**Issue by jayvdb** [mikekap/unicodedata2#1]
It would be great if this package provided installable wheels, so that users do not need to compile the package.

This would be especially useful for Python 2.6 and Python 2.7 on Linux, as Python 2.6.6, 2.7.0 and 2.7.1 have a regression in unicodedata.normalize NFC, and this backport may be the only 'solution' to allow support for those versions.  This is particularly important for Python 2.6.6, as it is the Python version provided by Redhat Enterprise Linux.
http://bugs.python.org/issue10254
https://phabricator.wikimedia.org/T102461

**Comment by jayvdb** [comment]
With appveyor builds now in place, I am happy to improve appveyor.yml to automatically generate and upload wheels to PYPI.  Are you OK with enabling Appveyor builds for this repo, and putting your PYPI user/pass into Appveyor's secure environment variables?

**Comment by mikekap** [comment]
Hmm I'm a little wary of automated wheel generation - although if there's a solid need, I could definitely add it. My impression is that wheels aren't really available for most python packages, and given the UCS-2 vs UCS-4 mess, they don't work quite well for py2. (e.g. my mac runs a UCS-4 build of python so I continuously have to add --no-use-wheel to every pip command).

But as I said, if there are non-trivial issues around building this package, I'd gladly add the wheels.

**Comment by jayvdb** [comment]
I'd appreciate wheels for win32, as win32 users tend to have problems compiling extensions.

**Comment by mikekap** [comment]
Added win32 wheels for 8.0.0. Feel free open another issue if I screwed something up (I just re-uploaded the appveyor wheels).
