### ISSUE TITLE
Unicode 10

### ISSUE THREAD

**Issue by anthrotype** [mikekap/unicodedata2#14]
Any plans for adding support for Unicode 10 which was released last month?
http://unicode.org/versions/Unicode10.0.0/
thanks!

**Comment by mikekap** [comment]
Yep definitely! Looks like a pretty easy upgrade too: https://github.com/python/cpython/commit/279a96206f3118a482d10826a1e32b272db4505d . I'll put it on my weekend list, though that has gotten pretty long (I don't use Python at my job anymore).

I would be more than happy to review a PR in the meantime though :)

**Comment by anthrotype** [comment]
Thank you @scw and @mikekap!
It would be nice to also have the wheels on PyPI.
https://pypi.org/project/unicodedata2 still shows 9.0.0

**Comment by mikekap** [comment]
@anthrotype all done, sorry for the wait. As a side note, `wheel` dropped support for some older versions of python (2.6 & 3.2) so there aren't any binary packages for those versions until `multibuild` fixes their setup.

**Comment by anthrotype** [comment]
Excellent, thanks a lot!
