### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by PanderMusubi** [mikekap/unicodedata2#19]
Please provide some pages with documentation containing examples of how to use this module. Here in the README and also at https://pypi.org/project/unicodedata2/ if possible

**Comment by mikekap** [comment]
This is a backport - the documentation is the same as the unicodedata package in python 3. The examples are there. I’ll add a link to that.

**Comment by PanderMusubi** [comment]
Thanks but still missing description at https://pypi.org/project/unicodedata2/ (`The author of this package has not provided a project description`) and link to https://pypi.org/project/unicodedata2/ in https://github.com/mikekap/unicodedata2/blob/master/README.md

**Comment by anthrotype** [comment]
I'll fix that, but that will only show up for the next release (and I don't think it's worth doing another release just for that).
