### ISSUE TITLE
Support localization

### ISSUE THREAD

**Issue by PanderMusubi** [mikekap/unicodedata2#20]
Please, support localization for Unicode block description and character description. Translations are available from https://github.com/unicode-table/unicode-table-data/tree/master/loc If possible, use a gettetxt approach similar to https://pypi.org/project/pycountry/ Implementing this feature will allow users to read Unicode descriptions in their own language, other than English.

For example, now is possible only in English:

    from unicodedata import name
    print(name('ß'))
    LATIN SMALL LETTER SHARP S

So unidecode could provide a way to translate LATIN SMALL LETTER SHARP S to e.g. German with (proposed code):

    from unicodedata import name
    from unicodedata2 import LOCALED_DIR
    from gettext import translation
    german = translation('UnicodeData2' LOCALED_DIR, languages=['de'])
    german.install()
    print(_(name('ß')))
    LATEINISCHER KLEINBUCHSTABE SCHARFES S

**Comment by mikekap** [comment]
This would be an awesome feature - that said, this should be part of core python. The goal of unicodedata2 is to provide a backport - not add any new functionality. I’d suggest filing a bug in the python issue tracker.

**Comment by PanderMusubi** [comment]
Thanks. Done with https://bugs.python.org/issue34053

**Comment by PanderMusubi** [comment]
Although it was received as a good idea, it was rejected as it is out of scope of the standard library. I have created this post https://groups.google.com/forum/#!topic/python-ideas/g2jj4WRVDFA to see how to get this implemented.
