### ISSUE TITLE
Unicode 12.1 Support

### ISSUE THREAD

**Issue by Harmon758** [mikekap/unicodedata2#29]
https://www.unicode.org/versions/Unicode12.1.0/
http://blog.unicode.org/2019/05/unicode-12-1-en.html
https://github.com/python/cpython/commit/3aca40d3cb4b9b6741cf3073d71fbfc682cab96d
https://github.com/python/cpython/pull/13214
https://bugs.python.org/issue36861

**Comment by anthrotype** [comment]
It would be nice to have a shell script to automate the process of updating the UCD data and synchronizing with latest CPython source. Or perhaps document how this is done manually.

**Comment by Harmon758** [comment]
It's primarily just updating `UNIDATA_VERSION` in both `makeunicodedata.py` and `makeunicodedata3.py`, and then running both scripts with Python 2 and 3, respectively. I then copy the `expected_checksum` for `test_unicodedata2.py` from the matching change to `test_unicodedata.py` in the corresponding CPython commit. After that, I run the tests and make sure the changes to the database match the CPython commit.

At this point, besides for documentation, the changes should fully match the CPython commit.
If there were any additional changes to `makeunicodedata.py` or `test_unicodedata.py`, those would need to be manually matched before running the script or tests. (In this case, in #30, I matched https://github.com/python/cpython/commit/6fec905de5c139017f36b212e54cac46959808fe as well, as that change was made prior to the Unicode 12.1.0 update.)

Finally, I update the changelog, the readme, and the version number in `setup.py`.

**Comment by anthrotype** [comment]
Thanks for the info! It looks like most of that could be automated. Maybe for next time then :)
