### ISSUE TITLE
Typing support

### ISSUE THREAD

**Issue by jack1142** [mikekap/unicodedata2#41]
Would you be interested in adding type stubs *if* they were contributed to this repo?
And if not, could you give me permission (*) to contribute the stubs to https://github.com/python/typeshed instead?

(*) The permission is required per [typeshed's contributing guidelines](https://github.com/python/typeshed/blob/master/CONTRIBUTING.md#core-developer-guidelines) but having the stubs for your lib in the typeshed does not require you to do any work on it as it's maintained within the typeshed repo then

**Comment by mikekap** [comment]
Go ahead if you'd like to contribute stubs to this repo, though that may be difficult. Feel free to add stubs either here or to the typeshed repo - whichever is easier.
