### ISSUE TITLE
Unicode 9.0 support?

### ISSUE THREAD

**Issue by anthrotype** [mikekap/unicodedata2#9]
any plans of adding support for Unicode 9.0?
thanks!

**Comment by mikekap** [comment]
I've mostly been backporting changes from cpython's repository. Looks like they just updated to 8.0.0. I'll try to get that out soon.

In terms of 9.0, I'm not terribly familiar with the changes. It's unfortunately not always `s/8/9/` so I'd rather wait until someone who knows what they're doing makes the changes. Feel free to make a PR, if you what to change :)
